spring.application.name=e-commerce-api
server.port=8095

# H2 Database
spring.datasource.url=jdbc:h2:file:C:/Users/speri/Desktop/e-commerce-api/backend/data/ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SpringDoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=MySecretKeyForJWTTokenGenerationThatIsLongEnough123456
jwt.expiration=86400000
